### ISSUE TITLE
Increase testing coverage by testing the backend better

### ISSUE THREAD

**Issue by vireshk** [rust-vmm/vhost-device#10]

**Comment by vireshk** [comment]
@jiangliu I looked at your tests for backend and they weren't helpful to increase the testing scope of vhost-device stuff.

I need to do something that emulates a real transaction with guest (Qemu for example from my setup). So I would create a real backend, i.e. use the vhu_i2c.rs as it is, but need something that fills the vrings, etc, just as a real guest/qemu setup would do. Any pointers ?

**Comment by andreeaflorescu** [comment]
@vireshk, we have the same problem in testing the virtio queues. For this purpose, we created a mock framework to help us initialize descriptor chains & fill the buffers with data (this part is still WIP).

You can take a look at [mock](https://github.com/rust-vmm/vm-virtio/blob/master/crates/virtio-queue/src/mock.rs) and how it is used in unit tests & benches. Maybe that helps.
