### ISSUE TITLE
Use predictable/persistent/stable/etc. names for gpio and i2c

### ISSUE THREAD

**Issue by vvavrychuk** [rust-vmm/vhost-device#164]
Currently device index is used for gpio/i2c, but in some cases same controller can have different index from boot to boot.

**Comment by vireshk** [comment]
@vvavrychuk I am not sure I understood the problem properly.

The device information is passed by the user while starting the daemon. Are you suggesting to pass a string for the name of the device instead, which the code should use to get the device index ?

**Comment by vvavrychuk** [comment]
Yes, exactly.

**Comment by vireshk** [comment]
@vvavrychuk I have tried an implementation, please see if it looks okay or not. Thanks.

**Comment by vireshk** [comment]
I2C is fixed. GPIO is left.

**Comment by vireshk** [comment]
There is no sane way of doing this for GPIO as discussed in the other pull request. Mark this resolved now.
