### ISSUE TITLE
Revisit pub types

### ISSUE THREAD

**Issue by vireshk** [rust-vmm/vhost-device#227]
For a binary crates, most of the types should be local to the crate. Revisit existing crates to see any violations.

**Comment by stsquad** [comment]
I'm surprised its not implied by the fact it is a binary crate. Can you even attempt to link it to a wider project?

**Comment by vireshk** [comment]
Maybe I am not sure. What if a binary crate wants to export some types so an external project can use them too ? Should be possible, but not required in our case.

**Comment by stsquad** [comment]
Anyway the change look good to me.
