### ISSUE TITLE
vsock: re-license as Apache-2.0 only

### ISSUE THREAD

**Issue by stefano-garzarella** [rust-vmm/vhost-device#234]
@harshanavkis (original author) acked here: https://github.com/rust-vmm/vhost-device/pull/216#discussion_r994430525

**Comment by stefano-garzarella** [comment]
I'll do this work (I can't assign to me from the UI)

**Comment by stefano-garzarella** [comment]
@vireshk `gpio`, `i2c`, and `rng` seems to have some licensing problems. In their Cargo.toml there is `license = "Apache-2.0 OR BSD-3-Clause"`, while in the files there is `// SPDX-License-Identifier: Apache-2.0`.

Should we fix Cargo.toml files?

**Comment by vireshk** [comment]
Sure, lets sync all of them at once.

**Comment by stefano-garzarella** [comment]
> Sure, lets sync all of them at once.

Okay, I'll do in the same PR.

**Comment by stefano-garzarella** [comment]
We decided to leave the vsock license as is (Apache-2.0 OR BSD-3-Clauses)
