### ISSUE TITLE
(vsock): infinte wait when a new connection is established

### ISSUE THREAD

**Issue by ramyak-mehra** [rust-vmm/vhost-device#307]
I don't really know how relevant this is but if we send a request which is less than `MIN_READ_LEN` the program just stalls

https://github.com/rust-vmm/vhost-device/blob/a3427f5c3402aa1a4cb679522154caf531d10d46/crates/vsock/src/vhu_vsock_thread.rs#L339-L341

**Comment by stefano-garzarella** [comment]
We can handle better this case in `read_local_stream_port()`, maybe providing some kind of error if `\n` is found earlier than expected.
