### ISSUE TITLE
How to let cloud-hypervisror communicate with the vhost RNG daemon

### ISSUE THREAD

**Issue by wangchao-sh** [rust-vmm/vhost-device#331]
start rng backend daemon:
`#vhost-device-rng --socket-path=/tmp/rng.sock -c 1 -m 512 -p 1000`

use ch-remote to let running cloud-hyperviosr communicate with the rng daemon:
`# ch-remote --api-socket /work/run/clh.sock add-user-device socket=/tmp/rng.sock0,id=rng0
Error running command: Server responded with an error: InternalServerError: ApiError(VmAddUserDevice(DeviceManager(VfioUserCreateClient(StreamRead(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))))`

`# ch-remote --api-socket /work/run/clh.sock add-device socket=/tmp/rng.sock0,id=rng0
Error running command: Error parsing device syntax: Error parsing --device: unknown option: socket`

The error occurs when using the add-device or add-user-device parameter.

**Comment by stsquad** [comment]
This looks like a problem on the cloud hypervisor side but you can run the daemon with:

```
env RUST_LOG=debug vhost-device-rng --socket-path=/tmp/rng.sock -c 1 -m 512 -p 1000
```

and you might get a bit more information on what is failing.

**Comment by mathieupoirier** [comment]
I have no background or context on this.  I will look into it in the coming
days.

**Comment by mathieupoirier** [comment]
@wangchao-sh What is "ch-remote"?  Can you provide more information on it?  As @stsquad mentionned, it seems to be a problem related to cloud-hypervisor.  It could also be an issue with priviliges.  I'm afraid not much can be done with the information currently provided.

**Comment by stefano-garzarella** [comment]
@wangchao-sh ping

Do you still have this problem or can we close this issue?

**Comment by stefano-garzarella** [comment]
No updates in the last year, I'm closing this. @wangchao-sh feel free to re-open if you still have the issue and more details
