### ISSUE TITLE
vsock: host listening, guest connecting partially works

### ISSUE THREAD

**Issue by ikicha** [rust-vmm/vhost-device#407]
Environment: crosvm
In the case of host listening and guest connecting, only first packet is delivered from host to guest. for guest-to-host works well.
And also guest listening scenario works well.

I suspect it's a kind of regression from https://github.com/rust-vmm/vhost-device/commit/7f809eeab8b50793a49c7c1c16205da531971152

It looks like epoll_register is called with different fds(for the first time, use the original fd, after that, it uses the cloned fd).

**Comment by stefano-garzarella** [comment]
@epilys can you take a look at the proposed fix?
It seems a regression we introduced with https://github.com/rust-vmm/vhost-device/commit/7f809eeab8b50793a49c7c1c16205da531971152

I can partially replicate also with QEMU, but the behavior is a bit different:
host$ socat - UNIX-LISTEN:/tmp/vm4.vsock_42
guest$ nc --vsock 2 42

I'm able to communicate and send multiple packets, but I see the following panic when closing the connection:
```
thread 'vring_worker' panicked at 'called `Option::unwrap()` on a `None` value', crates/vsock/src/vhu_vsock_thread.rs:327:70
```

#410 fixes that issue with QEMU
