### ISSUE TITLE
Potential Bug: The update of cid_map doesn't check confict cid.

### ISSUE THREAD

**Issue by zjhuang1008** [rust-vmm/vhost-device#432]
The update of cid_map uses insert() method which will update value if the map had the key before. The code below doesn't check the return value:
https://github.com/rust-vmm/vhost-device/blob/2fa80555d242f5aaa1d188cf79f982263c8bfd51/crates/vsock/src/vhu_vsock_thread.rs#L114C41-L114C41
It would happened if somebody writes a config which gives the same cid for different VMs on accident. It would be nice to have a conflict cid check in config parser.

**Comment by stefano-garzarella** [comment]
@zjhuang1008 thanks for opening the issue!

I think we should fail to create the vsock thread if the cid is already in the map.

@techiepriyansh do you have time to take a look?

Maybe we should also add a test to cover this scenarion.

**Comment by techiepriyansh** [comment]
@zjhuang1008 good catch!

I'll send a fix.
