### ISSUE TITLE
[BUG] vsock: Mem leak caused by circular referencing

### ISSUE THREAD

**Issue by cutelizebin** [rust-vmm/vhost-device#438]
## There might be a memory leak bug caused by circular referencing.

> VhostUserBackend ==> VhostUserVsockThread ==> VringEpollHandler
>          ^                                                                                  V
>          ||                                                                                   ||
>          ==================================
> 

There three struct refers to each other using Arc<T> , but no single line is using Weak<T>, which make it a circle.

And all these three struct cannot be dropped properly.

## Reproduction Process:
1. Launch vhost-device-vsock
2. Launch and kill QEMU or other VMM
3. Use top -Hp $(pgrep vhost-device-vsock) to watch the threads details

## Advice
Maybe we can use` Weak<VhostUserBackend>` in VringEpollHandler.

**Comment by cutelizebin** [comment]
> 

yes，I'll send a fix later on.

**Comment by stefano-garzarella** [comment]
This is also causing an issue after we merged commit 38caab24c5087551d6ec12d0002df798e5e4f5ac

When the VM reboot or shutdown, we have this error, instead of looping waiting for a new VM
```
ERROR vhost_device_vsock] Could not create backend: CID already in use by another vsock device
```

This happens because we have these cyclic references and `VhostUserVsockThread::drop()` is never invoked. So we don't remove the cid from the map.

**Comment by stefano-garzarella** [comment]
@cutelizebin do you have time to work on it? Otherwise, I can take a look ;-)

**Comment by stefano-garzarella** [comment]
@cutelizebin was easier than expected, we don't need to keep the `VringEpollHandler` reference in `VhostUserVsockThread`. I just sent #499 .

Thanks for reporting this!
