### ISSUE TITLE
gpio: Drop unsafe Send traits on structs including libgpiod structures

### ISSUE THREAD

**Issue by Ablu** [rust-vmm/vhost-device#442]
A new lint pointed out some weird `Arc<Mutex<>>` use that turned out to happen because we are (unsafely) extending the contract of libgpiod [1].

The following code is marking PhysDevice as `Send`:

https://github.com/rust-vmm/vhost-device/blob/802d09c542216b6f7beb1df30563fec5ba942946/crates/gpio/src/gpio.rs#L123-L128

`PhysDevice` is not `Send` automatically since `PhysLineState` contains `request::Request` which is not `Send` (because it contains a raw pointer).

Instead of just marking that as `Send`, the annotation in libgpiod needs to be fixed. Or - if that is not possible - we need to rewrite things so that the Send trait is not needed on PhysDevice. I am not immediately seeing anything that would disallow marking the line_request wrapper as Send, but it needs a discussion on whether libgpiod considers this as contract.

I kicked off a discussion around documenting libgpiod's threading safety guarantees [1]. Until that, we should silence the warning in order to keep CI happy. 

[1] https://github.com/rust-vmm/vhost-device/pull/435#issuecomment-1717205620
[2] https://lore.kernel.org/linux-gpio/CVHO091CC80Y.3KUOSLSOBVL0T@ablu-work/

/cc @vireshk

**Comment by stefano-garzarella** [comment]
@vireshk when you have time, can you take a look?

**Comment by Ablu** [comment]
I am working on a fix currently. Some cleanup patch is sent already:
https://lore.kernel.org/linux-gpio/20230927-chip-drop-arc-v1-0-28013bf95948@linaro.org/

Found some other issues that I am going through to fix.

**Comment by Ablu** [comment]
Turns out that this is more than a cosmetical marker issue. The (wrong) unsafe Sync impl is allowing API interactions that are unsafe according to libgpiod's threading rules. `process_event` is sharing a chip instance with other threads -which is unsafe. We will probably need to shuffle some mutexes around.

I will draft a patch.
