### ISSUE TITLE
dependabot: unignore vm-memory

### ISSUE THREAD

**Issue by stefano-garzarella** [rust-vmm/vhost-device#470]
`vm-memory` update to v0.13.0 is failing, so we ignored it for now.

Re-enable it when we are ready for the update.
This depends also on other crates (e.g `vhost`, `vhost-user-backend`).

**Comment by Ablu** [comment]
vhost dependency: https://github.com/rust-vmm/vhost/pull/190

**Comment by stefano-garzarella** [comment]
Asked to unignore it now that we have a new vhost release: https://github.com/rust-vmm/vhost-device/pull/528#issuecomment-1801338710
