### ISSUE TITLE
Add tests to increase code coverage for vhost-device-sound

### ISSUE THREAD

**Issue by dorindabassey** [rust-vmm/vhost-device#498]
The goal is to increase the code coverage percentage by adding a couple of small tests for the vhost-device-sound crate. Currently the alsa.rs testing module is not covered, you can consider adding test for alsa.rs or lib.rs(to be specific the Drop Impl for IOMessage is not covered yet).
you can run `cargo llvm-cov test --summary-only` in the staging crate to see the statistics of test covered and missed functions.

**Comment by stefano-garzarella** [comment]
We moved the device out from staging and covered most of the code with tests, so we can close this.
