### ISSUE TITLE
sound: tasks to move vhost-device-sound from staging

### ISSUE THREAD

**Issue by MatiasVara** [rust-vmm/vhost-device#578]
The purpose of this issue is to figure out what needs to be done to move `vhost-device-sound` from staging. Some of the tasks are:

- [x] Tests coverage, e.g., Alsa tests. This is fixed by https://github.com/rust-vmm/vhost-device/pull/579.
- [x] Pipewire bug, see https://github.com/rust-vmm/vhost-device/issues/538 and https://github.com/rust-vmm/vhost-device/issues/538#issuecomment-1812561519
- [x] Problem when compiling audio backends by using musl, see https://buildkite.com/rust-vmm/vhost-device-ci/builds/2105#018c47e1-bd2a-400c-bff3-47ba8e77ece0. This is fixed by #581. 

Is there anything else we need to do?

Thanks.

**Comment by epilys** [comment]
Sorry if I'm repeating myself, I legitimately don't remember where we settled for this; do we want musl builds or not?

**Comment by Ablu** [comment]
> Sorry if I'm repeating myself, I legitimately don't remember where we settled for this; do we want musl builds or not?

IIRC nobody was against disabling them where they do not make sense. But I am not sure whether we agreed on a way to do that.

**Comment by stefano-garzarella** [comment]
> Sorry if I'm repeating myself, I legitimately don't remember where we settled for this; do we want musl builds or not?

IIRC we agreed on disable musl build for the sound device. The problem was how. @Ablu suggested to take a look at the gpio device. I tried to see if we can do something in Cargo.toml, but without success. So IMHO for now we can do something similar of what we did in gpio.

**Comment by stefano-garzarella** [comment]
About `alsa` test, is someone working on it? (otherwise, I think we can put it in the `exclude_path`)

**Comment by epilys** [comment]
See #579

**Comment by stsquad** [comment]
Can this be closed now?

**Comment by MatiasVara** [comment]
> Can this be closed now?

We are thinking to keep it open until https://gitlab.freedesktop.org/pipewire/pipewire-rs/-/merge_requests/210 is merged, if that's OK.

**Comment by MatiasVara** [comment]
MR 210 has been merged, I close this issue.

**Comment by stefano-garzarella** [comment]
#606 is now merged, closing this ;-)
