### ISSUE TITLE
sound: release first version v0.1.0

### ISSUE THREAD

**Issue by stefano-garzarella** [rust-vmm/vhost-device#612]
The crate seems to be in good shape, so we may release the first version.

@dorindabassey @epilys @MatiasVara WDYT?

**Comment by epilys** [comment]
I think so too, may I publish it?

**Comment by stefano-garzarella** [comment]
@epilys yes please, go head!

**Comment by epilys** [comment]
Ah, I forgot, `pipewire-rs` must be published on crates.io first since we cannot publish with git dependencies. cc @dorindabassey

**Comment by dorindabassey** [comment]
OK I'll ask the pipewire-rs maitainer if he could make a release then.

**Comment by dorindabassey** [comment]
related PR [https://github.com/rust-vmm/vhost-device/pull/617](https://github.com/rust-vmm/vhost-device/pull/617)

**Comment by stefano-garzarella** [comment]
@epilys I think now we have everything ready. For me, we can release without any problems (I hope) :-)

**Comment by stefano-garzarella** [comment]
Released: https://crates.io/crates/vhost-device-sound
