### ISSUE TITLE
vsock: cargo-audit reports that `yaml-rust` is unmaintained

### ISSUE THREAD

**Issue by stefano-garzarella** [rust-vmm/vhost-device#639]
In vhost-device-vsock we use the `config` crate which now has a dependency that is unmaintained as `cargo audit` is reporting.

I reported to them here: https://github.com/mehcode/config-rs/issues/553

For now we don't have a new version available, so we can wait a bit or find an alternative.

**Comment by epilys** [comment]
An alternative would be to switch to `toml`, WDYT?

**Comment by stefano-garzarella** [comment]
> An alternative would be to switch to `toml`, WDYT?

yeah, I think we can wait a bit to understand their plan, if they will not fix it, we can switch to `toml`.
Not great as a change, but we are not stable at all, so it could be okay to change our config format.

**Comment by stefano-garzarella** [comment]
They just switched to `yaml-rust2` which seems maintained, so we just need to wait for a new `config` release. I asked about that.
