### ISSUE TITLE
sound: Tag and publish v0.2.0 release

### ISSUE THREAD

**Issue by epilys** [rust-vmm/vhost-device#686]
v0.2.0 was introduced in PR #685

**Comment by stefano-garzarella** [comment]
@epilys thanks on doing that, let me know if any help is needed!

**Comment by epilys** [comment]
Done! https://github.com/rust-vmm/vhost-device/releases/tag/vhost-device-sound-v0.2.0 https://crates.io/crates/vhost-device-sound 

Great job, everyone.
