### ISSUE TITLE
Create initial release for vhost-device-console and vhost-device-can

### ISSUE THREAD

**Issue by epilys** [rust-vmm/vhost-device#775]
See https://github.com/rust-vmm/vhost-device/pull/727#issuecomment-2478813549

**Comment by epilys** [comment]
- <https://github.com/rust-vmm/vhost-device/releases/tag/vhost-device-console-v0.1.0>
  crates.io <https://crates.io/crates/vhost-device-console>
- <https://github.com/rust-vmm/vhost-device/releases/tag/vhost-device-can-v0.1.0>
  crates.io <https://crates.io/crates/vhost-device-can>

CC @TimosAmpel

**Comment by TimosAmpel** [comment]
> * https://github.com/rust-vmm/vhost-device/releases/tag/vhost-device-console-v0.1.0
>   crates.io https://crates.io/crates/vhost-device-console
> * https://github.com/rust-vmm/vhost-device/releases/tag/vhost-device-can-v0.1.0
>   crates.io https://crates.io/crates/vhost-device-can
> 
> CC @TimosAmpel

@epilys thanks a lot ! :)
