### ISSUE TITLE
Create initial release for vhost-device-input

### ISSUE THREAD

**Issue by TimosAmpel** [rust-vmm/vhost-device#780]
Would it be possible to create an initial release for vhost-device-input?

**Comment by stefano-garzarella** [comment]
Ooops, we forgot about it. I can do it!

**Comment by TimosAmpel** [comment]
Thanks a lot @stefano-garzarella

**Comment by stefano-garzarella** [comment]
Just published https://crates.io/crates/vhost-device-input

Enjoy!
